In [1]:
try:
    from google.colab import drive
    drive.mount('/content/drive', force_remount=True)
    COLAB = True
    print("Note: using Google CoLab")
except:
    print("Note: not using Google CoLab")
    COLAB = False

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive
Note: using Google CoLab

In [6]:
## preprocess which year (16 or 11)
year=16

directory="/content/drive/My Drive/Colab Notebooks/India_Election_Analytics/polling stations-odd/ally_%d_output/"%year
file_prefix="ally_%d_" %year
file_suffix=".csv"

print(directory)
print(file_prefix)

/content/drive/My Drive/Colab Notebooks/India_Election_Analytics/polling stations-odd/ally_16_output/
ally_16_

In [0]:
import pandas as pd
import numpy as np

In [74]:
for n in range(117):
    # read files
    ac=2*n+1
    file=f"{directory}{file_prefix}{ac}{file_suffix}"
    ally_df=pd.read_csv(file)
    output_df=pd.DataFrame(columns=["AC_No","PS_No","Win_Alliance",\
                                    "W_A_Vote","Win_Party","W_P_Vote",\
                                    "2nd_Party","S_P_Vote"])

    ## get the party names 
    parties=ally_df.iloc[0,]

    ## get the votes
    votes=ally_df.iloc[1:-1,]

    ## turn the numeric objects to real numerics (float64)
    votes=votes.apply(pd.to_numeric,errors = 'coerce', axis=0)

    ## AC_No
    output_df[:len(votes),"AC_No"]=ac

    ## win_alliance
    output_df["Win_Alliance"]=votes.idxmax(axis=1)

    ## win_a_vote
    output_df["W_A_Vote"]=votes.max(axis=1)


    ##win_party
    win_party=parties[]

SyntaxError: ignored

In [125]:
## debug
ac=1
file=f"{directory}{file_prefix}{ac}{file_suffix}"
ally_df=pd.read_csv(file,index_col=0)
parties=ally_df.iloc[0,]
votes=ally_df.iloc[1:-1,]
votes=votes.apply(pd.to_numeric,errors = 'coerce', axis=0)

# output_df=pd.DataFrame(columns=["AC_No","PS_No","Win_Alliance",\
#                                 "W_A_Vote","Win_Party","W_P_Vote",\
#                                 "2nd_Party","S_P_Vote"])
## win_alliance
win_alliance=votes.idxmax(axis=1)
print(len(win_alliance))
#output_df["Win_Alliance"]=pd.concat([output_df["Win_Alliance"],win_alliance], ignore_index=True)

## win_a_vote
win_a_vote=votes.max(axis=1)
print(len(win_a_vote))

## win_party
win_party=pd.Series(parties[win_alliance]).reset_index(drop=True)
print(len(win_party))
print(win_party)
#output_df["Win_Party"].fillna(win_party,inplace=True)

## ps_no
print(len(votes))
print(len(votes.index))

## fill na in AC column with the current ac number
output_df=pd.DataFrame(data={"AC_No":[ac]*len(votes),
                             "PS_No":[int(i)+1 for i in votes.index], ## index starting from 1 (integer)
                             "Win_Alliance":win_alliance,
                             "W_A_Vote":win_a_vote,
                             "Win_Party":win_party,
                             "W_P_Vote":win_a_vote},
                       columns=["AC_No","PS_No","Win_Alliance",\
                                "W_A_Vote","Win_Party","W_P_Vote",\
                                "2nd_Party","S_P_Vote"])
# output_df.AC_No.fillna(ac,inplace=True)

print(output_df)

302
302
302
0      ADMK
1      ADMK
2      ADMK
3       PMK
4      ADMK
       ...
297     PMK
298    ADMK
299    ADMK
300     DMK
301     DMK
Name: 0, Length: 302, dtype: object
302
302

ValueError: ignored

In [98]:
display(votes)
print()
[ac]*

     AIADMK+  DMK  PWF  NDA  PMK  NTK  Others
0        407  164   12    4   28    1       6
1        331   90   12   12   17    1       9
2        317  132   21    0  190    3      23
3        173  120    5    3  412    5      29
4        381  263   16    7    5    6      13
..       ...  ...  ...  ...  ...  ...     ...
297      167  150    9    1  356    4      14
298      305  163   11    2   17    1      13
299      495  397   29    5   29    1      38
300      217  327   39    1    2    1       8
301      313  395    5    7    3    0      14

[302 rows x 7 columns]

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]