In [2]:
try:
    from google.colab import drive
    drive.mount('/content/drive', force_remount=True)
    COLAB = True
    print("Note: using Google CoLab")
except:
    print("Note: not using Google CoLab")
    COLAB = False

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive
Note: using Google CoLab

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
file="/content/drive/My Drive/Colab Notebooks/India_Election_Analytics/polling stations-odd/2016-odd.xlsx"
directory="/content/drive/My Drive/Colab Notebooks/India_Election_Analytics/polling stations-odd/ally_output/"

In [ ]:
alliance_names=["AIADMK+","DMK","PWF","NDA","NTK","PMK","Others"] ## unique alliances 

aiadmk_parties=["All India Anna Dravida Munnetra Kazhagam","ADMK","AIADMK",
                "Manithaneya Jananayaga Katchi","MJK",
                "Republican Party of India","RPI",
                "Samathuva Makkal Katchi","SMK","AISMK",
                "Tamil Nadu Kongu Ilaingar Peravai","TNKIP",
                "Mukkulathor Pulipadai","MP",
                "Tamil Maanila Muslim League","TMML"]
aiadmk_upper=[x.upper() for x in aiadmk_parties]

dmk_parties=["Dravida Munnetra Kazhagam","DMK",
             "Indian National Congress","INC",
             "Indian Union Muslim League","IUML",
             "Manithaneya Makkal Katchi","MMK","MAMAK",
             "Puthiya Tamilakam","PT",
             "Perunthalaivar Makkal Katchi","PMK",
             "Tamil Nadu Peasants and Workers Party","TNPWP",
             "Samuga Samathuva Padai","SSP"]
dmk_upper=[x.upper() for x in dmk_parties]

pwf_parties=["Desiya Murpokku Dravida Kazhagam","DMDK",
             "Marumalarchi Dravida Munnetra Kazhagam","MDMK",
             "Communist Party of India",\
             "Communist Party Of India Tamilaga Makkal Munnetra \
             Kazhagam Pattali Makkal Katchi Naam Tamilar Katchi","CPI",
             "Communist Party of India (Marxist)","CPI(M)","CPIM","CPI (M)",
             "Tamil Manila Congress","TMC","TMC(M)","TMC (M)",
             "Viduthalai Chiruthaigal Katchi","VCK"]
pwf_upper=[x.upper() for x in pwf_parties]


nda_parties=["Bharatiya Janata Party","BJP",
             "Indhiya Jananayaga Katchi","IJK"]
nda_upper=[x.upper() for x in nda_parties]

pmk_party=["Pattali Makkal Katchi","PMK" #independent]
pmk_upper=[x.upper() for x in pmk_parties]  
           
ntk_party=["Naam Tamilar Katchi","NTK", #independent]
ntk_upper=[x.upper() for x in ntk_parties]  

other_parties=["Tamilnadu Youth Party","TNYP",
        "KMDK",
        "NONE OF THE ABOVE","NOTA","SDPI",
        #...
        "Independent","INDI"]
other_upper=[x.upper() for x in other_parties]

alliance_dict=dict(zip(alliance_names,
                  [aiadmk_upper,dmk_upper,pwf_upper,nda_upper,other_upper]))

In [ ]:
def series_upper(series):
    ## change all strings to upper
    return series.str.upper()

def read_data(n): 
    ## input is constituency no.
    ## have to change it into the real no in the table
    ## starting from 0 sheet
    real_no=int((n-1)/2)
    data=pd.read_excel(file,sheet_name=real_no)
    data.fillna("None",inplace=True)
    return data

def get_alliance(data):
    alliances={}
    count=0
    for party in data.loc[1,data.loc[1,]!="None"].str.upper():
        count+=1
        for alliance, parties in alliance_dict.items():
            if party in parties:
                alliances[count]=alliance
        if count not in alliances.keys():
            alliances[count]="Others"
    alliances_=list(alliances.values())
    return alliances_

def get_ally_votes(data):
    alliances=get_alliance(data)

    temp_df=pd.DataFrame()
    temp_df=data.loc[2:len(data)-4,data.loc[1,]!="None"]
    temp_df.columns=alliances
    temp_df.reset_index(inplace=True,drop=True)

    output=pd.DataFrame()
    for name in alliance_names:
        temp=temp_df.loc[:,temp_df.columns==name]
        output[name]=temp.apply(sum,axis=1)

    ## total
    output.loc["Total"]=output.apply(sum)
    output.fillna(0,inplace=True)
    return output

In [167]:
odd_const=[(2*x+1) for x in range(117)]

for constituency in odd_const:
    print(constituency)
    data1=read_data(constituency)
    output_df=get_ally_votes(data1)
    output_df.to_csv(f"{directory}ally_{constituency}.csv")

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99
101
103
105
107
109
111
113
115
117
119
121
123
125
127
129
131
133
135
137
139
141
143
145
147
149
151
153
155
157
159
161
163
165
167
169
171
173
175
177
179
181
183
185
187
189
191
193
195
197
199
201
203
205
207
209
211
213
215
217
219
221
223
225
227
229
231
233

In [165]:
## debug
constituency=147
data1=read_data(constituency)
alliances=get_alliance(data1)

temp_df=pd.DataFrame()
temp_df=data1.loc[2:len(data1)-4,data1.loc[1,]!="None"]
temp_df.columns=alliances
temp_df.reset_index(inplace=True,drop=True)

output=pd.DataFrame()
for name in alliance_names:
    temp=temp_df.loc[:,temp_df.columns==name]
    print(temp)
    output[name]=temp.apply(sum,axis=1)


output.loc["Total"]=output.apply(sum)
output.fillna(0,inplace=True)
print(output)
# output_df=get_ally_votes(data1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[345 rows x 0 columns]
     DMK
0    173
1    205
2    374
3    400
4    213
..   ...
340  206
341  301
342  286
343  176
344  125

[345 rows x 1 columns]
    PWF
0    24
1    26
2    65
3    19
4    16
..   ..
340  32
341  24
342  20
343  12
344  18

[345 rows x 1 columns]
    NDA
0     1
1     8
2     5
3     2
4     4
..   ..
340   6
341   9
342   4
343   2
344   3

[345 rows x 1 columns]
    NTK NTK NTK NTK NTK NTK
0     6   4   0   2   1   6
1     6   5   2   1   1   0
2    21  23   1   0   3  12
3     7  16   1   2   7  13
4    12  12   1   1   3  11
..   ..  ..  ..  ..  ..  ..
340   4   1   0   0   1   9
341   7   5   3   1   1  10
342   6   3   0   1   1  16
343   4   5   0   2   5  14
344   4  10   0   2   1   5

[345 rows x 6 columns]
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[345 rows x 0 columns]
    Others Others Others Others Others
0        2    338      0      0      1
1        2    244      0      1      0
2        2    409      0      6      5
3        0    461      1      5      6
4        2    448      1     10      9
..     ...    ...    ...    ...    ...
340      0    223      4      0      0
341      1    371      0      1      3
342      0    444      0      1      6
343      1    352      0      1      6
344      2    316      0      2      5

[345 rows x 5 columns]
       AIADMK+      DMK      PWF     NDA      NTK  PMK    Others
0          0.0    173.0     24.0     1.0     19.0  0.0     341.0
1          0.0    205.0     26.0     8.0     15.0  0.0     247.0
2          0.0    374.0     65.0     5.0     60.0  0.0     422.0
3          0.0    400.0     19.0     2.0     46.0  0.0     473.0
4          0.0    213.0     16.0     4.0     40.0  0.0     470.0
...        ...      ...      ...     ...      ...  ...       ...
341        0.0    301.0     24.0     9.0     27.0  0.0     376.0
342        0.0    286.0     20.0     4.0     27.0  0.0     451.0
343        0.0    176.0     12.0     2.0     30.0  0.0     360.0
344        0.0    125.0     18.0     3.0     22.0  0.0     325.0
Total      0.0  99709.0  12045.0  2198.0  12181.0  0.0  109157.0

[346 rows x 7 columns]